# Generated by Django 4.2.19 on 2025-02-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=1, max_length=15, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'FICTION'), ('non-fiction', 'NON-FICTION'), ('technology', 'TECHNOLOGY')], max_length=20),
        ),
    ]
