# Generated by Django 4.2.19 on 2025-03-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_created_at_alter_book_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='1', max_length=15, unique=True, verbose_name='ISBN'),
        ),
    ]
