# Generated by Django 4.2.19 on 2025-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_average_rating_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'FICTION'), ('Non-fiction', 'NON-FICTION'), ('technology', 'TECHNOLOGY')], max_length=20),
        ),
    ]
